# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfversion < Formula
  desc "A simple tool to manage Terraform versions"
  homepage "https://github.com/tfversion/tfversion"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tfversion/tfversion/releases/download/v0.0.6/tfversion_0.0.6_darwin_arm64.tar.gz"
      sha256 "1736d7fb19bc2f8ee62fb4b0e67861ad627c6a6e2af3b65d8e5057567ec55240"

      def install
        bin.install "tfversion"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tfversion/tfversion/releases/download/v0.0.6/tfversion_0.0.6_darwin_amd64.tar.gz"
      sha256 "7337c927a70202bb2fb830b30d8e9a6a2a306b6f5a4e281144655e8d78090686"

      def install
        bin.install "tfversion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tfversion/tfversion/releases/download/v0.0.6/tfversion_0.0.6_linux_arm64.tar.gz"
      sha256 "14d2f1010a4f7e5e159504d8f84bcb97d3a28283cab09ea8607dc55a05df8ab4"

      def install
        bin.install "tfversion"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tfversion/tfversion/releases/download/v0.0.6/tfversion_0.0.6_linux_amd64.tar.gz"
      sha256 "306a650fccb041c55b6473d9f75e0a8f0771e477d6a06a616399d94c81a75b45"

      def install
        bin.install "tfversion"
      end
    end
  end

  test do
    system "#{bin}/tfversion -v"
  end
end
