# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfversion < Formula
  desc "A simple tool to manage Terraform versions"
  homepage "https://github.com/tfversion/tfversion"
  version "0.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tfversion/tfversion/releases/download/v0.1.9/tfversion_0.1.9_darwin_arm64.tar.gz"
      sha256 "c4cca6fa5d3087ce191fac72d602d9616c79bd7f301eee33378b63925bc04cac"

      def install
        bin.install "tfversion"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tfversion/tfversion/releases/download/v0.1.9/tfversion_0.1.9_darwin_amd64.tar.gz"
      sha256 "c606974da3c99a01566b22b0ac77038018483bbcc23fb5df55711452682226e7"

      def install
        bin.install "tfversion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tfversion/tfversion/releases/download/v0.1.9/tfversion_0.1.9_linux_arm64.tar.gz"
      sha256 "c8571356c8a49e5d5a91e70f612d13413a1b14d12dcf29cdf4e76b9a1c913bcb"

      def install
        bin.install "tfversion"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tfversion/tfversion/releases/download/v0.1.9/tfversion_0.1.9_linux_amd64.tar.gz"
      sha256 "fb5b2d4d2a7efc78b04160a54167e6cebf182f024e235c8cff4f6e9115382cd0"

      def install
        bin.install "tfversion"
      end
    end
  end

  test do
    system "#{bin}/tfversion -v"
  end
end
